// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/user/interface.go

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	user "github.com/program-world-labs/DDDGo/internal/application/user"
	entity "github.com/program-world-labs/DDDGo/internal/domain/user/entity"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// GetByIDUseCase mocks base method.
func (m *MockIService) GetByIDUseCase(ctx context.Context, id string) (*user.Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDUseCase", ctx, id)
	ret0, _ := ret[0].(*user.Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDUseCase indicates an expected call of GetByIDUseCase.
func (mr *MockIServiceMockRecorder) GetByIDUseCase(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDUseCase", reflect.TypeOf((*MockIService)(nil).GetByIDUseCase), ctx, id)
}

// RegisterUseCase mocks base method.
func (m *MockIService) RegisterUseCase(ctx context.Context, userInfo *entity.User) (*user.Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUseCase", ctx, userInfo)
	ret0, _ := ret[0].(*user.Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUseCase indicates an expected call of RegisterUseCase.
func (mr *MockIServiceMockRecorder) RegisterUseCase(ctx, userInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUseCase", reflect.TypeOf((*MockIService)(nil).RegisterUseCase), ctx, userInfo)
}
