app:
  name: "ai-service"
  version: "0.0.1"

http:
  port: "8080"

swagger:
  host: "localhost:8080"

kafka:
  brokers: "localhost:29092,localhost:29093,localhost:29094"
  group_id: "ai-dev"

logger:
  project: ""
  log_level: "debug"
  log_id: "ai-dev"

sql:
  host: "localhost"
  port: 5432
  user: "user"
  password: "pass"
  db: "db"
  type: "postgresql"
  pool_max: 1
  connection_attempts: 3
  connection_timeout: 1

# sql:
#   host: "localhost"
#   port: 3306
#   user: "user"
#   password: "pass"
#   db: "db"
#   type: "mysql"
#   pool_max: 1
#   connection_attempts: 3
#   connection_timeout: 1

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

# nosql:
#   host: "localhost"
#   port: 27017
#   user: ""
#   password: ""
#   db: "ai-service"
#   type: "mongodb"

storage:
  host: "localhost:9000"
  bucket: "ai-service"
  type: "gcp"

telemetry:
  enabled: true
  port: 0
  batcher: "gcp"
  sample_rate: 1.0
