app:
  name: 'ai-service'
  version: '0.0.1'

http:
  port: '8080'
  backend_port: '8088'

redis:
  dsn: 'redis://localhost:6379/0'

swagger:
  backend_host: 'localhost:8088'
  frontend_host: 'localhost:8080'

logger:
  log_level: 'debug'
  log_id: 'ai-dev'

postgres:
  pool_max: 2
  url: "postgres://user:pass@localhost:5432/postgres?sslmode=disable"

gcp:
  project: ''
  credentials: ""
  emulator: true
  firestore: 'localhost:8090'
  auth: 'localhost:9099'
