basePath: /v1
definitions:
  adapter.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
  role.CreatedRequest:
    properties:
      description:
        example: this is for admin role
        maxLength: 200
        type: string
      name:
        example: admin
        maxLength: 30
        type: string
      permissions:
        example:
        - read:all
        - write:all
        items:
          type: string
        type: array
    required:
    - description
    - name
    - permissions
    type: object
  role.Response:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      permissions:
        items:
          type: string
        type: array
      updatedAt:
        type: string
      users:
        items:
          $ref: '#/definitions/user.Response'
        type: array
    type: object
  user.Response:
    properties:
      avatar:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a translation service as an example
  title: Go Clean Template API
  version: "1.0"
paths:
  /role/create:
    post:
      consumes:
      - application/json
      description: Create role
      operationId: CreateRole
      parameters:
      - description: Role Create Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/role.CreatedRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/adapter.Response'
            - properties:
                data:
                  $ref: '#/definitions/role.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/adapter.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/adapter.Response'
      summary: Create role
      tags:
      - Role
swagger: "2.0"
